### ISSUE TITLE
Testing examples in the Docs

### ISSUE THREAD

**Issue by BeckySharp** [lum-ai/odinson#104]
Testing

Now that the docs are live: http://gh.lum.ai/odinson/
We should make a unit test from each of the examples provided.  
There are currently several examples, likely some more will be added, but there are enough to get started.

Thanks!

**Comment by gcgbarbosa** [comment]
Things to test:

- [ ] Token Constraints http://gh.lum.ai/odinson/token_constraints.html
- [ ] Graph traversals: http://gh.lum.ai/odinson/graph_traversals.html
- [ ] Basic Queries http://gh.lum.ai/odinson/basic_queries.html
- [ ] Event Queries (to be done)
- [ ] Quantifiers http://gh.lum.ai/odinson/quantifiers.html
- [ ] Strings http://gh.lum.ai/odinson/strings.html
