### ISSUE TITLE
Support event-like mentions in state

### ISSUE THREAD

**Issue by myedibleenso** [lum-ai/odinson#11]
Currently, the state is unaware of arguments/attributes, so we essentially only support textbound ("flat") mentions.  Ultimately, though, we'll want to be able to handle mentions with named (and typed) arguments (cf. Odin).

### Requirements
- many-to-many database structure
- Mention data structure (and flavors thereof)
- ???

**Comment by BeckySharp** [comment]
Now that we have Event Mentions and progress on the State, we should revisit this
@marcovzla @myedibleenso

**Comment by kwalcock** [comment]
The first version is "in", waiting to be merged.

**Comment by kwalcock** [comment]
It was merged.
