### ISSUE TITLE
Move the rule learning code

### ISSUE THREAD

**Issue by danebell** [lum-ai/odinson#118]
@kevinlum commented on [Mon Jun 29 2020](https://github.com/lum-ai/eidos-causeex/issues/215)

Then Robert: move the rule learning code there.

---

@MihaiSurdeanu commented on [Wed Jul 15 2020](https://github.com/lum-ai/eidos-causeex/issues/215#issuecomment-658900714)

@danebell : this belongs in odinson

**Comment by danebell** [comment]
@robertvacareanu , you should be able to see/edit https://github.com/lum-ai/rule-learning-plugin now

**Comment by kevinlum** [comment]
done
