### ISSUE TITLE
Add listener/control process

### ISSUE THREAD

**Issue by danebell** [lum-ai/odinson#119]
@kevinlum commented on [Mon Jun 29 2020](https://github.com/lum-ai/eidos-causeex/issues/216)

Robert: add listener/control process to rule learning. Also, keep in mind that rule learning is more than binary relations. Minimally, we should learn unary relations as well.

**Comment by kevinlum** [comment]
Done, but tricky to include in BE, 1 user assumed
Need to match user and request
Need multi user support.
