### ISSUE TITLE
Greedy quantifiers

### ISSUE THREAD

**Issue by myedibleenso** [lum-ai/odinson#12]
Currently Odinson quantifiers are neither greedy nor lazy.  The greedy v. lazy distinction is, however, essential moving forward.  Consider a naive rule fragment for detecting an NP: 

```
[tag=/N.*/]+
```
The current behavior is to return all (or all tiled?) possible matches, rather than the longest.  This clutters the state and is counter-intuitive to the user considering the syntax and standard meaning of the `+` quantifier.

**Comment by marcovzla** [comment]
This has been fixed for a while now.
