### ISSUE TITLE
Run benchmarks

### ISSUE THREAD

**Issue by kevinlum** [lum-ai/odinson#126]
Using a few rules (events) benchmark 100, 1k, 100k docs (run flight recorder on the code)  

Run benchmarks based on refined criteria (from above)

**Comment by gcgbarbosa** [comment]
- Sample datasets:
- [ ] 100
- [ ] 1k
- [ ] 100k
- [ ] Build indexes and put them available using some free storage service
- [ ] Build the grammar (@BeckySharp will help with eidos grammars)
- [ ] Run
- [ ] Profile
- [ ] Write report
- [ ] Write documentation on how to replicate

**Comment by gcgbarbosa** [comment]
I am closing this for now, and then re-open later if we need.
