### ISSUE TITLE
Convert tests to object

### ISSUE THREAD

**Issue by kevinlum** [lum-ai/odinson#141]
Convert tests from string representation to object

**Comment by gcgbarbosa** [comment]
- [x] start and end markers
- [x] positive and negative lookaheads
- [ ] concatenation and disjunctives
- [ ] graph traversals
- [ ] graph traversals wildcards
- [ ] lazy repetitions
- [ ] greedy repetitions
- [ ] constraints

**Comment by kevinlum** [comment]
Blocked - push to Aug 11

**Comment by BeckySharp** [comment]
This was tabled for now, the decision was to write tests for the AST instead of the QueryCompiler.
test file was removed with #189.
