### ISSUE TITLE
Import in grammars

### ISSUE THREAD

**Issue by kevinlum** [lum-ai/odinson#153]
Import in grammars, review with Marco on existing Odin code. Draft for custom URL option as regular expression (how will registering work tbd later)

**Comment by myedibleenso** [comment]
@kwalcock @marcovzla @danebell Long ago when the Earth was still young, we talked about defining and registering new protocols to unambiguously specify file system vs JAR-relative imports.  

Being able to use a repo address (with support for a specific commit, branch head, etc.) for a grammar or (sub-grammar) would be wonderful.

**Comment by BeckySharp** [comment]
maybe we can scope the effort in 2 parts:
- add support for imports using a method that will (in the future) support
the repo address (with support for a specific commit, branch head, etc.)
for a grammar
- add that support for repo address (with support for a specific commit,
branch head, etc.) for a grammar

?

What methods are viable for this?

**Comment by myedibleenso** [comment]
I think also having `file://` and `jar://` would be great.

>What methods are viable for this?

I believe we had discussed a [custom protocol handler](https://www.oreilly.com/library/view/learning-java/1565927184/apas02.html) before as one potential solution.

**Comment by BeckySharp** [comment]
Plan -- pass a File not String to compileRules, then support relative paths.  Start there, open a draft PR
