### ISSUE TITLE
Tests for REST API

### ISSUE THREAD

**Issue by myedibleenso** [lum-ai/odinson#158]
We need some foundational tests for the REST API.  

This will require ...

- A test index to hit and inspect responses to ensure they conform to the [OpenAPI specification](https://github.com/lum-ai/odinson/blob/3531b5676297d7cf959fb78b127043181c44ede2/backend/public/schema/odinson.yaml)
  - This will require injecting the config at test time.

- Establishing a testing framework for the `backend` subproject ([likely using `org.scalatestplus.play`](https://www.playframework.com/documentation/2.8.x/ScalaTestingWithScalaTest)). 

_Minimally_ (or to start anyway), we need to test the following endpoints: 
 - [`/api/execute/pattern`](https://github.com/lum-ai/odinson/blob/3531b5676297d7cf959fb78b127043181c44ede2/backend/conf/routes#L15)
 - [`/api/execute/grammar`](https://github.com/lum-ai/odinson/blob/3531b5676297d7cf959fb78b127043181c44ede2/backend/conf/routes#L17)

**Comment by myedibleenso** [comment]
The creation of the test index should itself be a test (the index shouldn't be committed as resource).  

To create that index, we'll want to commit an Odinson doc or two as test resources.

**Comment by gcgbarbosa** [comment]
As discussed with @myedibleenso, I will write the tests for the `extra` package following the steps:

- [ ] figure out how to inject code in `extra` package
- [ ] add 2 documents as an example inside the resources for the extra package (test .gz and .json if possible)
- [ ] write tests for the index creation process
- [ ] make sure the process of creating an index can be imported as a fixture

**Comment by maxaalexeeva** [comment]
@myedibleenso, do you think this is done enough to close?

**Comment by myedibleenso** [comment]
Yes.
