### ISSUE TITLE
Page build warning for missing theme

### ISSUE THREAD

**Issue by myedibleenso** [lum-ai/odinson#159]
Looks like doc theme we're using isn't supported by GH Pages:

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> You are attempting to use a Jekyll theme, "just-the-docs", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://docs.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://docs.github.com/articles/troubleshooting-jekyll-builds

It looks like we can [either a) fork a theme and specify its repo with `remote_theme` in the page's yaml config or b) change to one of the supported themes](https://docs.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll).

**Comment by BeckySharp** [comment]
IDK that we need to fork a repo etc, we are specifying the `remote_theme`, maybe we can just delete the "theme"  line?
@gcgbarbosa are you up for checking? i forgot how to build it locally to check that it still looks right if i delete the "theme" line and just leave the "remote_theme"

**Comment by BeckySharp** [comment]
in the meantime, it works fine, just issues a warning by email

**Comment by myedibleenso** [comment]
Sure.  I didn't know you were specifying `remote_theme` already (I hadn't looked at the docs config).  

The only real advantage to forking the theme is if you want control over what happens to it.

I get emailed the warning every time a new commit is made to master, so I'd prefer to get rid of it (or disable notification of the warning).

**Comment by gcgbarbosa** [comment]
Idk what the warning looks like, but we might be getting the error bc I am specifying the theme twice, once remote and once normally, so that the person does not have to change anything when working offline. 
I did not know this was causing a warning. 
I guess we can just comment out the second and it should work, but then we would have to re-enable it to see the theme when working offline.

**Comment by gcgbarbosa** [comment]
This is the line I am talking about: https://github.com/lum-ai/odinson/blob/04760b07e7c8c6c60d9c61234f5a41c92c8257c3/docs/_config.yml#L3

**Comment by myedibleenso** [comment]
@gcgbarbosa , you can't pull in a remote theme when working locally?

**Comment by gcgbarbosa** [comment]
Let me test...

**Comment by myedibleenso** [comment]
Based on [this SO response](https://stackoverflow.com/a/50403126), I'm thinking we just need to add `gem "jekyll-remote-theme"` to this section:

- https://github.com/lum-ai/odinson/blob/04760b07e7c8c6c60d9c61234f5a41c92c8257c3/docs/Gemfile#L13-L19

**Comment by gcgbarbosa** [comment]
It seems to be working without the line. Can you check if you are still getting the warning?

**Comment by BeckySharp** [comment]
any chance we can "check" by merging this and quickly seeing that (a) we don't get the warnign email and (b) the docs still look pretty?

**Comment by BeckySharp** [comment]
they're still pretty, thanks @gcgbarbosa  and @myedibleenso !
