### ISSUE TITLE
Allow quantification over sequences of surface token and graph edges

### ISSUE THREAD

**Issue by hillelt** [lum-ai/odinson#18]
Not sure if this is a bug or an intended behavior, but it seems that the current Odinson pattern language doesn't allow for parenthesis over a combination of surface token and graph edges. e.g. in Odin it was easy to capture an optional chain of verbs through a pattern like `(>> [tag=/^V.*/])*` but such a syntax does not compile in Odinson.

**Comment by BeckySharp** [comment]
@marcovzla I added this to this week's sprint, but if we need more time we can adjust that

**Comment by BeckySharp** [comment]
@hillelt -- this request was long enough ago, you may well not be interested, but just so you know,  this was addressed with #140 
🎉 
If you find errors we'd be interested to know, thanks!
