### ISSUE TITLE
State query not working for basic pattern using SQL state

### ISSUE THREAD

**Issue by BeckySharp** [lum-ai/odinson#181]
@kwalcock I noticed that the state queries aren't working with basic patterns in the SQL state.  @marcovzla and I tried to swap to the Memory state, but it's not fully implemented.  I added a failing test on the `state_issue` branch.
The `second` query succeeds, but the semantically equivalent `third` query fails.
I think we need your help here, but if you want to point us in the right direction, we can help fix it.
Thanks!

**Comment by kwalcock** [comment]
I'll look into it.  The MemoryState is not up to date.  A refresh of that is high on the list.

**Comment by kwalcock** [comment]
#182
