### ISSUE TITLE
can I use metadata?

### ISSUE THREAD

**Issue by dvzhang** [lum-ai/odinson#246]
**How can we help you?**
![image](https://user-images.githubusercontent.com/42195071/106482361-5703f700-64e8-11eb-9644-4633e3971424.png)
can I use metadata? just like paper _Odinson: A Fast Rule-based Information Extraction Framework_ said

**Comment by danebell** [comment]
Hi, @dvzhang. Yes, you can use metadata to filter your results using lucene-style queries. This is accomplished through

1. Creating the [metadata](https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/core/src/main/scala/ai/lum/odinson/OdinsonDocument.scala#L14) along with each document. Metadata creation from Processors documents is [not yet implemented](https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/extra/src/main/scala/ai/lum/odinson/extra/ProcessorsUtils.scala#L45-L49) in the Utils, but a custom method could add this data from a separate data store without much change or extension. To help with this, the [TokensField](https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/core/src/main/scala/ai/lum/odinson/OdinsonDocument.scala#L71-L81) and [DateField](https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/core/src/main/scala/ai/lum/odinson/OdinsonDocument.scala#L126-L150) classes have implicit converters from JSON.
2. Submitting a query of the parent document (which contains the document metadata) in addition to the other queries, using [mkParentQuery](https://github.com/lum-ai/odinson/blob/fe0701778da42950e808c24481975d842b216711/core/src/main/scala/ai/lum/odinson/compiler/QueryCompiler.scala#L50). You can see an example of this being applied in Odinson's API [here](https://github.com/lum-ai/odinson/blob/fe0701778da42950e808c24481975d842b216711/backend/app/controllers/OdinsonController.scala#L206-L211).

Hope this helps! Please feel free to follow up.

**Comment by BeckySharp** [comment]
@danebell  @dvzhang -- FWIW i'd be really interested to know if the OdinsonWebapp supports these, so if you get them "ready", would you be up for updating me so I know if I need to make changes over there?

**Comment by danebell** [comment]
To expand on what I wrote above, there are [two existing API endpoints](https://github.com/lum-ai/odinson/blob/edc78378f0c1c10fc9f2de14c540d1b415a1e843/backend/conf/routes#L15-L18) that use `parentQuery` to encode metadata queries.

**Comment by danebell** [comment]
@BeckySharp If you mean the IDE, AFAIK it's not supported yet. But what you say does make me think I should open an issue. The older version of the IDE does support parent queries, but I don't think it will work without serious updates.

**Comment by BeckySharp** [comment]
@danebell I don't mean the IDE or the OdinsonUI, I was referring to https://github.com/BeckySharp/OdinsonWebapp

**Comment by dvzhang** [comment]
> Hi, @dvzhang. Yes, you can use metadata to filter your results using lucene-style queries (like `location:Tucson`). This is accomplished through
> 
> 1. Creating the [metadata](https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/core/src/main/scala/ai/lum/odinson/OdinsonDocument.scala#L14) along with each document. Metadata creation from Processors documents is [not yet implemented](https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/extra/src/main/scala/ai/lum/odinson/extra/ProcessorsUtils.scala#L45-L49) in the Utils, but a custom method could add this data from a separate data store without much change or extension. To help with this, the [TokensField](https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/core/src/main/scala/ai/lum/odinson/OdinsonDocument.scala#L71-L81) and [DateField](https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/core/src/main/scala/ai/lum/odinson/OdinsonDocument.scala#L126-L150) classes have implicit converters from JSON.
> 2. Submitting a query of the parent document (which contains the document metadata) in addition to the other queries, using [mkParentQuery](https://github.com/lum-ai/odinson/blob/fe0701778da42950e808c24481975d842b216711/core/src/main/scala/ai/lum/odinson/compiler/QueryCompiler.scala#L50). You can see an example of this being applied in Odinson's API [here](https://github.com/lum-ai/odinson/blob/fe0701778da42950e808c24481975d842b216711/backend/app/controllers/OdinsonController.scala#L206-L211).
> 
> Hope this helps! Please feel free to follow up.

Thanks for your reply!
I try to make an annotated file like this to try metadata queries. But it doesn't work
![image](https://user-images.githubusercontent.com/42195071/106629288-a49a6580-65b5-11eb-9ea3-9ba9cb93f52e.png)

so, I have two questions:
1. can you give me an annotated file that I can use to try metadata queries? I can learn from it.
2. can you tell me how to do to Submitting a query of the parent document? in the shell? or something else?
Thanks for your help!

**Comment by BeckySharp** [comment]
adding @myedibleenso in case it's helpful

**Comment by myedibleenso** [comment]
I don't believe is supported in the shell.  

I'll take a look at this request tonight and see if I can generate/locate an MWE using the REST API.

**Comment by BeckySharp** [comment]
I'd also like to support this in the OdinsonWebapp -- so I'm interested in
knowing what I need to do to make that happen.
Thanks!

**Comment by myedibleenso** [comment]
Quick update:

I'm working on a [simple example](https://github.com/clu-ling/odinson-example), but I may have stumbled on a bug/lost functionality.  Unfortunately, it looks like it may take a bit longer than originally anticipated.  Glad this issue was opened, though!

**Comment by dvzhang** [comment]
> Quick update:
> 
> I'm working on a [simple example](https://github.com/clu-ling/odinson-example), but I may have stumbled on a bug/lost functionality. Unfortunately, it looks like it may take a bit longer than originally anticipated. Glad this issue was opened, though!

Thanks a lot!

**Comment by myedibleenso** [comment]
@dvzhang , way later than intended, but the documentation and unit tests now illustrate how metadata queries can be used.  If you have further questions, we can reopen this issue, but I'm closing for now.
