### ISSUE TITLE
Store specific fields

### ISSUE THREAD

**Issue by myedibleenso** [lum-ai/odinson#248]
Currently, the `OdinsonIndexWriter` is written such that either a) all fields are stored if `storeAllFields` is `true` or b) only the `displayField` is stored.  

In ancient times when magic still existed in the world, each and every `Field` had an attribute denoting whether or not that field should be stored [that went away with this commit](https://github.com/lum-ai/odinson/commit/b556e53f9f4cd9a5945adf53afec80dfae6a39de#diff-f32db8f6c06a0bcd34c0c67e7dfdea60028b41e769d7307e9a542c00476efa0c)).  

In the interest of flexibility, I think a nice middle ground/compromise here would be to introduce `storedFields` in the config, which would be a list of field names that should be stored, and then pass this to the `OdinsonIndexWriter` in place of `storeAllFields` (ex. `storedFields: List[String]`). This would allow us to store things like metadata/parent doc fields without bloating the index with certain token attributes and other sentence-level information.

**Comment by BeckySharp** [comment]
sounds awesome, want me to do the honors or will you?

**Comment by BeckySharp** [comment]
@myedibleenso think we should have a file that accompanies the index that lists the stored field names, similar to the file that has the dependencies vocab, so that projects which use the index know what things they can directly get from the index as a stored field?

I could be over thinking this.
The reason for being able to store fields is so that things are easier downstream, like getting the text of mentions, the lemmas, etc, so we can do filtering by content etc. without having to go to the Odinson docs each time.

**Comment by myedibleenso** [comment]
>think we should have a file that accompanies the index that lists the stored field names, similar to the file that has the dependencies vocab, so that projects which use the index know what things they can directly get from the index as a stored field?

+1

I think, though, maybe we should consider making that a json file (ex. `config.json`) with different entries in case we end up needing to add other information like this in the future.  That would document the settings used to create an index.

**Comment by BeckySharp** [comment]
Cool -- want me to work on that?

**Comment by myedibleenso** [comment]
If you're up to it, that would be great (should we get input from others first?).   I'm still trying to figure out what's wrong with parent queries.  The problem I found apparently wasn't the only one...

**Comment by BeckySharp** [comment]
ok, we can wait for X amount of time, sounds wise.  Anything I can do to help debug the parent queries?

**Comment by myedibleenso** [comment]
@BeckySharp, during today's casual touch base, this came up and everyone seemed on-board with the plan.

**Comment by BeckySharp** [comment]
cool -- i'll check it out, thanks :)
