### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by kwalcock** [lum-ai/odinson#250]
I figured.  I think we should add [Scalafmt](https://scalameta.org/scalafmt/) as a plugin, decide on a config, and add the formatting as an CI hook to enforce a consistent style across the repo.

_Originally posted by @myedibleenso in https://github.com/lum-ai/odinson/issues/243#issuecomment-771161912_

**Comment by kwalcock** [comment]
@myedibleenso wrote the above and @danebell responded with :+1: and then it was brought up briefly by @BeckySharp at the meeting of Feb. 8 in which it suggested that I look into it a little more.

Gus, even knowing the name of this thing, probably knows about it more than I do, so he should chime in.  Also notice that in the `.gitignore` file of this project, it looks like George inserted the lines
```
# scala formater
.scalafmt.conf
```
so some people may have been using this already.

I made a branch `scalafmt` in which the tool is configured to work for `IntelliJ` and `sbt` in various ways.  One can use 
```
Opt + Cmd + L (macOS)
Ctrl + Alt + L (other)
```
to format the current file.  Perhaps the people working on `odinson` would like to try it and check out the format and decide whether it is worth pursuing.

If it is, we would need to do things like configure it for an agreed upon format, see if there is a way to override the settings when needed*, set IntelliJ and other tools to format on save, run the formatter over all the code and make one PR with only formatting changes, figure out how to integrate it with GitHub or some other process, etc.  I'll be looking into the latter things unless someone says they already know how to do them.

*For instance, I see that someone has carefully formatted this code in a kind of table
```
      first.docIndex, // luceneDocId
      docId,          // luceneSegmentDocId
      docBase,        // luceneSegmentDocBase
      idGetter,
      first.name,     // foundBy
```
and it might be worth preserving that kind of thing.

FWIW I'm happy with how well we've worked together and how neat, consistent, flexible, considerate we've been with shared code and projects. :grinning:

**Comment by kwalcock** [comment]
I don't really like that the formatter seems to need to run on the developer's machine.  It would be nice to run it on the server.

**Comment by BeckySharp** [comment]
at least in the past, in a diff team, we were able to add a pylinter to the
continuous integration thing or whatever so that your PR would be checked
for formatting too online (travis?)

**Comment by kwalcock** [comment]
There's a https://github.com/marketplace/actions/scalafmt-action that I hadn't seen before.

**Comment by myedibleenso** [comment]
Yes, after adding the plugin, we can configure it to run on compile and/or run it as part of CI.  That part is pretty straightforward.  The hard part is deciding on a style! : )

**Comment by myedibleenso** [comment]
>I don't really like that the formatter seems to need to run on the developer's machine. It would be nice to run it on the server.

@kwalcock , running _only_ as a CI hook adds some complexity related to committing formatting changes using a bot account.  I've set things up now to check that the formatting was run, but it is ultimately still up to the contributor (or the PR reviewer) to run the formatting task locally and commit any changes in order for all of the CI checks to pass.  I mentioned this in the PR, but it looks like the recommended workflow is to configure your editor/IDE to run scalafmt on save.  Apparently running the task on compile is not advised for performance reasons.

**Comment by kwalcock** [comment]
Thanks.  Glad I'm not the PR person.

**Comment by kwalcock** [comment]
It looks like they may have taken the vertical alignment of comments, as mentioned above, into consideration based on https://github.com/scalameta/scalafmt/issues/1242 .

**Comment by kwalcock** [comment]
From https://scalameta.org/scalafmt/docs/configuration.html:

There is a possibility to override scalafmt config for a specific code with // scalafmt: {} comment
Disable formatting for specific regions of code by wrapping them in // format: off blocks

**Comment by kwalcock** [comment]
See #252.
