### ISSUE TITLE
Documentation refers to `Example` that does not exist in latest tagged version

### ISSUE THREAD

**Issue by courtarro** [lum-ai/odinson#251]
**Describe the bug**
The [Walkthrough Example](http://gh.lum.ai/odinson/walkthrough.html) in the documentation says "choose `Example` off the list", but `ai.lum.odinson.extra.Example` is newer than v0.2.3 (the latest tagged version), so it does not yet exist in that version. I realize this is software under heavy development, but it's unclear to a new user (like me) which version of Odinson is the best one to install. Starting from the latest tagged version (even though it's ~11 months old) is a natural first step, but it led me to run into this issue.

**To Reproduce**
1. Run `sbt extra/run`

**Expected behavior**
Based on the documentation, I would expect `ai.lum.odinson.extra.Example` to be listed as a choice, but it did not exist in version 0.2.3.

**Options to resolve**
- Update the documentation to explicitly advise installing `master`, or another, newer tag rather than version 0.2.3
- Remove the reference to `Example`
- Release a new version that includes `Example`

Thanks!

**Comment by BeckySharp** [comment]
@courtarro thanks for this -- we needed a good kick in the pants about it :)
Also, Sorry we didn't respond to you sooner -- we TOTALLY agree with all your points, took your plea seriously, called a meeting, and are working to release 0.3.0 this week.  If you can wait that long, that's really the best way to do this.
Again, thank you and please feel free to follow up on this with more comments/questions/accountability :)

**Comment by courtarro** [comment]
Sounds great! I'll watch for the next release. Thanks!

**Comment by BeckySharp** [comment]
thanks for your patience/understanding (and again, thanks for your nudge!!)
