### ISSUE TITLE
ExtractorEngine.getTokens() should rely on config for determining raw field

### ISSUE THREAD

**Issue by myedibleenso** [lum-ai/odinson#27]
Currently the ExtractorEngine's `.getTokens() method assumes the doc's `rawTokenField` is "raw":

- https://github.com/lum-ai/odinson/blob/552b49c55c4ef4b8b26da14a665f5531c16265d0/core/src/main/scala/ai/lum/odinson/ExtractorEngine.scala#L143

Everywhere else these fields are determined via the config or by passing config-derived fields to constructors.

**Comment by BeckySharp** [comment]
@myedibleenso I think this has been addressed by your displayField change.  Should we close this?

**Comment by myedibleenso** [comment]
I think it was only partially address, but resolving it would involve only a very minor change.

Basically, we'd want "raw" in the call above to be tied to the config (which should default to "raw").

**Comment by BeckySharp** [comment]
unless I'm missing something, the call currently (in master) uses the displayField, which is filled in from the config and defaults to `raw`

**Comment by myedibleenso** [comment]
Oops!  I was looking at the versioned link : ) 🤦 

Thanks for pointing that out.  Yes, let's close this.  It seems to be resolved.
