### ISSUE TITLE
Metadata filters in grammars

### ISSUE THREAD

**Issue by BeckySharp** [lum-ai/odinson#301]
As a user I can add metadata filters to the grammar files, so that I can use metadata filters on all my rules so that they're applied only on the specified docs.

- add parsing in the RuleReader, make sure applies the right way to all imported files
- add tests
- once there, add support in the extractors OR at least make sure the queries have them so that when EE does extractMentions the filters are applied

**Comment by myedibleenso** [comment]
Should these be rule-level, grammar-level, or both?

**Comment by myedibleenso** [comment]
Closed via #322
