### ISSUE TITLE
How to modify/constrain the same token using multiple dependency relations in a basic query?

### ISSUE THREAD

**Issue by victoryhb** [lum-ai/odinson#321]
Thank you all so much for this amazing and unique piece of software.

When experimenting with the Odinson query language in the Odinson shell, I couldn't find any documentation/examples of how to specify multiple modifying dependency relations for the same token, e.g. how to "and" the relations, using basic queries. It appears that event queries, which are much more complex and incompatible with the shell, can do this partially, but then, they don't seem to support querying of sequences of surface forms as basic queries do?
In StanfordNLP's Semgrex, which is similar in syntax to Odinson's basic query, all relations are relative to first node in the string. So to express the meaning of "a node that is the governor of both an nsubj relation and a dobj relation", we can simply say:
{} >nsubj {} >dobj {}

Contrast this with one of the examples on the [Shell's page](http://gh.lum.ai/odinson/shell.html), where the pattern
(?<cause> []) leads to (?<effect> [])
is used to identify the effect, but the word immediately following "to" is often not the target noun (but determiners etc.). A more appropriate pattern might allow us to specify that we want the word "lead" to be followed by "to" AND be the head of a oblique nominal (the effect).

I wonder if there's a way to do this in Odinson's basic queries?

**Comment by BeckySharp** [comment]
I think you're likely looking for an "event" rule.

In an event rule, the argument patterns are all relative to the `trigger`, so you can add multiple constraints.  Here's an example of an event rule for `"a node that is the governor of both an nsubj relation and a dobj relation"` (AFAIK you can't use event rules in the shell, but you can in the grammars and in [OdinsonWebapp](https://github.com/BeckySharp/OdinsonWebapp).

```
- name: testrule
   type: event
   pattern: |
      trigger = []
      subject = >nsubj []
      object = >dobj []
```

If you want multiple token constraints you can chain those with `&`, e.g., if you don't care _what_ the outgoing nsubj/dobj connect to, you could also do this:

    [outgoing=nsubj & outgoing=dobj]

In terms of the second query, you could specify this:

    lead  (?=to)  >nmod_to (?<effect> []) 

(depending on what processor you use, the dep names will be diff)
here, the `(?= to)` is a lookahead, and the to won't be captured.

**Comment by BeckySharp** [comment]
@victoryhb here's a screenshot from the OdinsonWebapp showing what gets extracted from a toy corpus I have with that query:
![image](https://user-images.githubusercontent.com/5384073/127718204-9bff4076-5d99-4860-9091-444ce4300987.png)

**Comment by victoryhb** [comment]
@BeckySharp Thanks a lot for your informative reply! 
Thanks for confirming that this is possible with an event rule (your OdinsonWebapp is very useful BTW), and teaching me a few tricks with the basic query I didn't find in the docs (the lookahead trick is a godsend!) I can now combine event and basic rules to match very complex patterns.

I have one more question though:
Is it possbile to embed the trigger from an event rule into another basic or event rule?
For example, if I want to match a "somebody saw something" pattern in the following sentence:
I saw some very big fish in the river.
"fish" is the _dobj_ of "saw", and I want to constrain "fish" so that it must have an adjectival modifier (>amod) AND a prepositional modifier (>nmod_in). Embedding an event rule in another rule seems to be the only way to do this, right? But I haven't found any relevant examples in the docs.

Thanks.

**Comment by BeckySharp** [comment]
> @BeckySharp Thanks a lot for your informative reply!
> Thanks for confirming that this is possible with an event rule (your OdinsonWebapp is very useful BTW), and teaching me a few tricks with the basic query I didn't find in the docs (the lookahead trick is a godsend!) I can now combine event and basic rules to match very complex patterns.

I'm sorry the lookahead (and the look behinds too) aren't in the docs, I'll open an issue for them to get added! Sorry, the docs seem to be ever a work-in-progress...!
> 
> I have one more question though:
> Is it possbile to embed the trigger from an event rule into another basic or event rule?
> For example, if I want to match a "somebody saw something" pattern in the following sentence:
> I saw some very big fish in the river.
> "fish" is the _dobj_ of "saw", and I want to constrain "fish" so that it must have an adjectival modifier (>amod) AND a prepositional modifier (>nmod_in). Embedding an event rule in another rule seems to be the only way to do this, right? But I haven't found any relevant examples in the docs.
> 
> Thanks.

I think there are two ways of doing this.  
Directly with something like this:

   ```[] >dobj (?<result> []) (?= [outgoing=/nmod_in/ & outgoing=/amod/])```

Or in a 2-"pass" grammar that first finds the things like fish in the example above and then goes through and looks for structures where those previously found things are the dobj of something of interest (like "saw").  something like:
```
- name: example-rule2
    type: basic
    priority: 1
    label: Fishlike
    pattern: |
       [outgoing=/nmod_in/ & outgoing=/amod/]
   
  - name: example-rule3
    type: event
    priority: 2
    label: saw
    pattern: |
       trigger = [tag=/V.*/]
       subj = >nsubj
       constrained_object: Fishlike = >dobj
```

**Comment by victoryhb** [comment]
@BeckySharp Thank you for the great examples, both of which seem to be working nicely. However, it appears that with the suggested solutions it is not possible to capture and return the modifier ("big") and the location ("river"). (Sorry for not explicitly mentioning the need for this earlier). What I want to express is something like the following, in Semgrex syntax:

{tag:NN}=fish >amod {}=modifier >nmod_in {}=location

I wonder if it is possible in Odinson?
Thanks.

**Comment by myedibleenso** [comment]
@victoryhb , you're wanting to capture a triple `{fish, modifier, location}`, right?  Are you wanting to restrict the first match the the token "fish" or words like halibut etc?

Assuming you're not constraining the token you want to associate with `fish`, this pattern will work:

```
(?<fish>) >amod (?<modifier> []) >nmod_in (?<location>[])
```

If you wanted to ensure that the `fish` arg only matches the token "fish", we could add an additional token constraint:

```
(?<fish> [lemma=fish]) >amod (?<modifier> []) >nmod_in (?<location>[])
```

Let's imagine instead that you want to match any sequence of nouns for `fish` and `location`:

```
(?<fish>[tag=NN]+) >amod (?<modifier> []) >nmod_in (?<location> [tag=NN]+)
```

As written, these variants are not really constrained to match a true **location**, so they'll overmatch (ex. "mysterious sequences in DNA").


Let's imagine you've run a statistical NER over your document collection prior to indexing, and that locations are tagged with the NE label `LOCATION`:


```
(?<fish>[tag=NN]+) >amod (?<modifier> []) >nmod_in (?<location> [tag=NN & entity=LOCATION]+)
```

If you want to label the encompassing span with `FishyDream`, you could use something like this:


```yaml

 - name: fish-triple
    type: basic
    priority: 1
    label: FishyDream
    pattern: |
       (?<fish>[tag=NN]+) 
       >amod (?<modifier> []) 
       >nmod_in (?<location> [tag=NN & entity=LOCATION]+)
```

Does that help to answer your question?

**Comment by victoryhb** [comment]
@myedibleenso Thanks a ton for the detailed examples!
A bit of background here: as a linguistics researcher, I am concerned with the flexibility of Odinson's syntax to deal with arbitrarily complex definitions of dependency relations (so that I can use it to retrieve different linguistic patterns from large corpora, like using the powerful yet much slower Semgrex). The "fish" sentence is just a simplified example to showcase my problem with the definition of multiple dependency relations constraining the same token.

So far I am having the following problems with constraining the "fish" token with dependency relations:
(1)
As per your examples, the order in which we place the dependency relations appears significant: 
`(?<fish>[]) >amod (?<modifier> []) >nmod_in (?<location>[]) `
only matches >amod relations AFTER the "fish" token (e.g. "fish, which are big, in the river")
while
`(?<modifier>[]) <amod (?<fish>[]) >nmod_in (?<location>[]) `
only matches those BEFORE (e.g. "big fish in the river"")
There seems no easy way to match both cases at the same time, right? And what if we have more than two dependency relations?

(2)
I couldn't find a way to embed the above basic rule into an event rule, so that it serves as a component in the event rule (e.g. "fish" as a dobj dependent of the verb "saw"), and capture and return the original named dependents ("big", "river" etc.) of "fish".
That's the problem I am having with @BeckySharp's suggested solutions.

**Comment by BeckySharp** [comment]
> (2)
> I couldn't find a way to embed the above basic rule into an event rule, so that it serves as a component in the event rule (e.g. "fish" as a dobj dependent of the verb "saw"), and capture and return the original named dependents ("big", "river" etc.) of "fish".
> That's the problem I am having with @BeckySharp's suggested solutions.

if you want to capture the dependents, you can convert the first rule of the pair I presented above into an event rule, like this:

    name: example-rule2
    type: basic
    priority: 1
    label: Fishlike
    pattern: |
       trigger = []
       mod = >amod
       location = >nmod_in

this will capture all the info, and it will be available to you in the other found mention, as its argument will be this mention (i.e. it will be nested but captured).

**Comment by victoryhb** [comment]
@BeckySharp Thanks. The fish token may only be a small part of a complex rule, and my current problem is how to embed something like example-rule2 into other rules and use it to constrain other elements in those rules (e.g. define an event rule whose trigger is constrained by the trigger of example-rule2 - "fish" is the dobj of "saw" in the rule; or define a basic rule that uses the Fishlike pattern like a single element so that we can say: saw >dobj Fishlike).

**Comment by BeckySharp** [comment]
@victoryhb so at the moment there is no way to embed one event-rule-type-pattern (i.e., a trigger and paths defined from the trigger) in the argument of another, aside from doing this as a two-pass as above.  Note that doing it as a two-pass isn't awful, as it's pretty fast.

Notice that in example-rule3 above, the argument is required to be of type "Fishlike" (here, basically meaning it has to have been constrained the way you specified, a previously found mention).

You can also use a prev found mention as a trigger, like this:

```
  - name: example-rule3
    type: event
    priority: 2
    label: saw
    pattern: |
       trigger = @Fishlike
       subj = >nsubj
       constrained_object: Fishlike = >dobj
```
Here it doesn't make a lot of sense bc of the way the other rule works (i.e., Fishlike mentions are objects, not verbs)

FWIW, we are discussing adding the expressivity you're mentioning, something like:

```
  - name: example-rule-combined
    type: event
    priority: 2
    label: saw
    pattern: |
       trigger = [tag=/V.*/]
       subj = >nsubj
       constrained_object: Fishlike = >dobj {"mod": >amod, "location": >nmod_in }
```
But we (a) haven't decided the syntax yet and (b) how to incorporate it in the runtime system.  There is no eta on it, but we are looking.  In the meantime I think you can get a lot of mileage out of making multiple passes.

**Comment by victoryhb** [comment]
@BeckySharp Thanks. The multiple-pass solution you suggested solves the bulk of my problem so I will use that for now. I look forward to seeing the new and even more expressive syntax in the future.
Thank you all for your kindness and patience over the past few days. I wish the project a great success.
I am closing this issue now.

**Comment by myedibleenso** [comment]
@victoryhb , thanks for providing that additional information about your use case.  I wanted to mention that Odin (the slower precursor to Odinson) has a feature that you might find useful. With Odin, it's possible to reference arguments of a mention in another rule/pattern using the `@MentionLabel.argname` syntax:

https://github.com/clulab/processors/blob/1d006a12a0d419af5eab710173846785a8cee013/main/src/test/scala/org/clulab/odin/TestTokenPattern.scala#L827

That example uses a surface or token pattern, but the same feature works for graph-based rules (ex. traversals of a syntactic dependency graph).

While Odin is nowhere near as fast as Odinson, it might be worth benchmarking if this feature serves your needs.

**Comment by victoryhb** [comment]
@myedibleenso Thank you for mentioning the Odin feature which seems a very expressive syntax that meets my needs. I will check it out and look forward to seeing it implemented in Odinson (since query speed is such an important factor for many use cases:)
