### ISSUE TITLE
Why are some results found by an event rule not properly matched?

### ISSUE THREAD

**Issue by victoryhb** [lum-ai/odinson#332]
I am using the REST API to query the following example grammar in a corpus processed by the FastNLPProcessor:
```
rules:
 - name: "example"
   label: GrammaticalSubject
   type: event
   pattern: |
     trigger = [lemma=have]
     subject = >nsubj
     object = >dobj
```
I found that in addition to the correct captures, many (about two thirds) results are returned without actually capturing all the arguments, although by definition they do match the rule. For example:
```
 {'documentId': 'HEV',
               'foundBy': 'example',
               'label': null,
               'match': [{'captures': [], 'span': {'end': 6, 'start': 5}}],
               'sentenceId': 446,
               'sentenceIndex': 446,
               'words': ['They',
                         'had',
                         'some',
                         'big',
                         'musical',
                         'shows',
                         'there',
                         '.']},
```
I wonder if these are the intended results or a bug?

**Comment by BeckySharp** [comment]
are you referring to the span of the mention? Event mention spans are the spans of the trigger. Or is it the case that you’re truly not getting the arguments?  I am less familiar with the API, more familiar with the core code and the OdinsonWebapp.

**Comment by victoryhb** [comment]
@BeckySharp I mean I am not getting the defined arguments (subject, object, and the trigger itself etc.). In a grammar with only one rule, I'd expect the system to return results that match the rule, like the following:

```
    {'documentId': 'EVM',
     'foundBy': 'example',
     'label': 'GrammaticalSubject',
     'match': [{'captures': [{'subject': {'captures': [],
                                          'span': {'end': 5,
                                                   'start': 4}}},
                             {'object': {'captures': [],
                                         'span': {'end': 10,
                                                  'start': 9}}}],
                'span': {'end': 7, 'start': 6}}],
     'sentenceId': 1404,
     'sentenceIndex': 661,
     'words': ['Compact',
               'is',
               'a',
               'separate',
               'initiative',
               'which',
               'has',
               'no',
               'direct',
               'relationship',
               'with',
               'any',
               'Examination',
               'Board',
               '.']},
```
and not return any results that don't match. What puzzles me is many results are returned that apparently match the rule, but unlike normal results, their label is 'None' and they don't provide information about the captured arguments like the above example.

**Comment by BeckySharp** [comment]
I suspect what you're seeing are the argument mentions that are correctly attached to the event, but not displaying in a way you're expecting.  Can you paste the full output here so we can "walk through it"?  Alternatively, I can try to help you viz your output in this webapp? https://github.com/BeckySharp/OdinsonWebapp
Which isn't a replacement for the API but can help you understand the output better.

**Comment by victoryhb** [comment]
> I suspect what you're seeing are the argument mentions that are correctly attached to the event, but not displaying in a way you're expecting. 
Ah, that indeed appears to be the case! The results for the same matched sentence appear twice in the returned json, one with the correct mentions and one without (the latter may be some kind of intermediate output?). Since the two versions are not adjacent to each other (but usually several results apart), I did not recognize them immediately. For my purpose, I will just ignore those whose label is null then. Thanks a lot! @BeckySharp

**Comment by BeckySharp** [comment]
@victoryhb happy to help!
