### ISSUE TITLE
How to return the original JSON document of each matched sentence?

### ISSUE THREAD

**Issue by victoryhb** [lum-ai/odinson#334]
The REST-API currently returns matches in the form of mentions, but sometimes we need the original JSON document (like the one we fed to the indexer) of each match (so as to, say, build front-end syntactic visualizations of the matches). I wonder if there is a way to do so?

P.S. While I have no prior knowledge about Scala, I am experimenting with Odinson's source through the sbt console (through trial and error, I now know how to make a query using the ExtractorEngine to return some OdinResults). So a few code examples would be extremely helpful. Thanks!

**Comment by myedibleenso** [comment]
Hi, @victoryhb .  You should be able to do this using the REST API's `/api/parent/by-document-id` endpoint.  That also allows you to circumvent using Scala directly.  : )

**Comment by myedibleenso** [comment]
After launching the REST API, you can open the docs page (`/api`) to use this endpoint interactively and view its documentation.

**Comment by victoryhb** [comment]
Thank you @myedibleenso! I tested the by-document-id endpoint a bit and was able to obtain the JSON of a document by its id.
However, the API appears to be limited to one document at a time, and in my case it took several seconds to retrieve one doc by id. Looking at the source code, I see that to retrieve the JSON for a matched sentence, we will need to:
(1) get the doc and sentence id of each matched sentence
(2) read and deserialize the JSON file corresponding to the doc id
(3) return the sentence's JSON by looking up the doc with the sentence id
This may be quite inefficient when the documents are large and there are many matches. In our current use case, we'd like to retrieve the JSON of all matches to get the statistical distribution of associated tags of each token in a mention.
I thought since the document JSON is already indexed, it should be relatively straightforward to retrieve them from Lucene? I scoured the code but couldn't find the related functions :(.

**Comment by myedibleenso** [comment]
>This may be quite inefficient when the documents are large and there are many matches. 

Yes, it will be very inefficient.  Another option is to get the set of doc IDs for all matches before attempting to retrieve any docs.  You might also consider indexing smaller documents (ex. sentences, paragraphs, chapters, etc).  The smaller docs could share metadata (ex. title) and have a metadata field indicating their intended order.  

>In our current use case, we'd like to retrieve the JSON of all matches to get the statistical distribution of associated tags of each token in a mention.

Do you need the *entire* document or just the sentence containing each mention?  If just the sentence, you can use `/api/sentence`, but this will still be inefficient if the docs are large.  

>I thought since the document JSON is already indexed, it should be relatively straightforward to retrieve them from Lucene? 

It's possible to reconstruct a sentence field by field by requesting and deserializing each field from the index as you suggested, but this only works if you've stored everything at index time.  We did not implement sentence retrieval that way, because there is no guarantee a user will always store all fields.  If you allow for that flexibility (ie.., the ability to produce a lean index), the only surefire method is to retrieve from disk.



# Recommendation
For the use case you describe, I suggest ... 

1. breaking each document into many smaller documents and then indexing.  
2. first collecting the **set** of doc/sentence ids across all matches before attempting to retrieve that data.

**Comment by victoryhb** [comment]
> Do you need the entire document or just the sentence containing each mention?  If just the sentence, you can use /api/sentence, but this will still be inefficient if the docs are large.

Yes, we need just the sentence, but from the code it appears that the retrieval mechansim of ```/api/sentence``` is almost the same as ```/api/parent/by-document-id``` (both require reading/deserializing the entire doc from file)? Following your recommendation, if we index at the sentence level, then the **set** of matched doc ids will be roughly the same as the **list** of matched doc ids (since ids in the latter are roughly unique), so the increase in efficiency might still be limited?

> It's possible to reconstruct a sentence field by field by requesting and deserializing each field from the index as you suggested, but this only works if you've stored everything at index time. We did not implement sentence retrieval that way, because there is no guarantee a user will always store all fields.

We have no problem storing everything at index time, because we know exactly what we put into and get out of the index. From my experimentation, I know we can get the indexed doc using an ExtractorEngine object, like:
`val doc = extractorEngine.doc(docId)`
and retrieve the indexed fields. But it appears that the syntactic dependency data are not found in the returned doc object. Any tips on how to get those?

**Comment by myedibleenso** [comment]
>from the code it appears that the retrieval mechansim of /api/sentence is almost the same as /api/parent/by-document-id (both require reading/deserializing the entire doc from file)

Yes, that's right.  You'll only really see a performance improvement if you index smaller documents. 

>then the set of matched doc ids will be roughly the same as the list of matched doc ids (since ids in the latter are roughly unique)

I suppose that depends on your rules.  For example, if you have a grammar where several rules are likely to match the same sentence, you're going to end up with many duplicates in the list of doc IDs.

The efficiency improvement comes from avoiding to load many large text files only to retrieve short snippets (sentences).

>But it appears that the syntactic dependency data are not found in the returned doc object. Any tips on how to get those?

While not impossible, I'm afraid it would be be fairly involved.  There aren't any convenience methods for doing that as of yet.

Given your use case, I think storing each sentence as a document and retrieving via the REST API will be the fastest option.

**Comment by victoryhb** [comment]
Okay, I see. Thank you for your kind help! @myedibleenso
