### ISSUE TITLE
Possible bug with token offsets/results in REST API query response 

### ISSUE THREAD

**Issue by curtkohler** [lum-ai/odinson#338]
I'm seeing some oddities in the token & offsets in some of my basic query responses.  I've narrowed down to a simple test case using the != operator on a single sentence.

The basic sentence in play is:  Topical imiquimod and fluorouracil are also potential , but less supported , treatments .

The text has had DRUG entities previously identified and DRUG tagged tokens have an entity value in the form of: |DRUG:\<name\>|
In this sentence the tokens: imiquimod,  fluorouracil are tagged as DRUGs on the entity axis, all of the other tokens are tagged as '0' for the entity.

Running a simple rest API query of:  (?<notdrug_green>[entity!=/|DRUG.*/]) 

I would have expected to get every token except the two drug names returned as match spans, but instead I am seeing tokens starting with the token 'also' being returned in the response. I'm not sure why the earlier non-DRUG tokens (Topical, and, are) aren't being identified.

Here is the actual REST API result payload returned for that sentence for that query (I'm also attaching the JSON input doc to this issue):

{
      "sentenceId": 29,
      "score": 0,
      "documentId": "S0002838X12602470",
      "sentenceIndex": 29,
      "words": [
        "Topical",
        "imiquimod",
        "and",
        "fluorouracil",
        "are",
        "also",
        "potential",
        ",",
        "but",
        "less",
        "supported",
        ",",
        "treatments",
        "."
      ],
      "matches": [
        {
          "span": {
            "start": 5,
            "end": 6
          },
          "captures": [
            {
              "notdrug_green": {
                "span": {
                  "start": 5,
                  "end": 6
                },
                "captures": []
              }
            }
          ]
        },
        {
          "span": {
            "start": 6,
            "end": 7
          },
          "captures": [
            {
              "notdrug_green": {
                "span": {
                  "start": 6,
                  "end": 7
                },
                "captures": []
              }
            }
          ]
        },
        {
          "span": {
            "start": 7,
            "end": 8
          },
          "captures": [
            {
              "notdrug_green": {
                "span": {
                  "start": 7,
                  "end": 8
                },
                "captures": []
              }
            }
          ]
        },
        {
          "span": {
            "start": 8,
            "end": 9
          },
          "captures": [
            {
              "notdrug_green": {
                "span": {
                  "start": 8,
                  "end": 9
                },
                "captures": []
              }
            }
          ]
        },
        {
          "span": {
            "start": 9,
            "end": 10
          },
          "captures": [
            {
              "notdrug_green": {
                "span": {
                  "start": 9,
                  "end": 10
                },
                "captures": []
              }
            }
          ]
        },
        {
          "span": {
            "start": 10,
            "end": 11
          },
          "captures": [
            {
              "notdrug_green": {
                "span": {
                  "start": 10,
                  "end": 11
                },
                "captures": []
              }
            }
          ]
        }

[S0002838X12602470.json.txt](https://github.com/lum-ai/odinson/files/7238499/S0002838X12602470.json.txt)

**Comment by danebell** [comment]
Thanks for bringing this to our attention, @curtkohler. I'll reproduce and get back to you.

**Comment by danebell** [comment]
Thanks again for bringing this to our attention, @curtkohler. The latest snapshot should now work as expected.
