### ISSUE TITLE
Odinson totalHits slows down queries when there are many matches

### ISSUE THREAD

**Issue by mcshlain** [lum-ai/odinson#36]
**Is your feature request related to a problem? Please describe.**
This issue is related to #35, which makes odinson unusable on large corpora with patterns that occur frequently. This feature will mitigate the problem partially and I think it's a good feature to have regardless of the issue. 

**Describe the solution you'd like**
I would like to control the behavior of counting all match hits via a configuration flag to speed the queries up (by not  computing the totalHits).

**Describe alternatives you've considered**
Another approach is to have this as a parameter to the the request itself but it will not be consistent with how pageSize is defined. (also in the global configuration). 
I think the distinction between what configuration is global and what should be controllable per query is a separate issue. 

**Additional context**
I've submitted a PR for this: #34

**Comment by marcovzla** [comment]
closed by #34
