### ISSUE TITLE
Broken link to Odinson REST API repository in docs/index.md

### ISSUE THREAD

**Issue by adarshp** [lum-ai/odinson#374]
**Documentation type:** End-user documentation

**Improvements requested:** The link to the Odinson REST API repository in the documentation  (https://github.com/lum-ai/odinson-rest) leads to a 404 (Page not found) error.

**Link (if available):** https://github.com/lum-ai/odinson/blob/c160833af07133dcd07b617d22bb0c891c74d5a9/docs/index.md?plain=1#L24

**Comment by myedibleenso** [comment]
Thanks for the issue.  The rewrite of the REST API is not yet publicly available.  I'll go ahead and remove the link for the time being.
