### ISSUE TITLE
Odin --> Odinson for extractions from individual text fragments.

### ISSUE THREAD

**Issue by adarshp** [lum-ai/odinson#375]
We are currently using Odin for extracting entities and events from spoken natural language in real-time (https://github.com/clulab/tomcat-text).

I am curious about the potential of using Odinson to speed up rule development for our project. Two questions come to mind:

1. Does Odinson have an API component to extract mentions from a single fragment of text (as opposed to a corpus)?
1.1 If the answer to (1.) is no, is Odinson backward compatible with Odin rules?
1.2 If the answer to (1.) is yes, could you point us to the API component (the Scala method will do, but if there is a REST API already implemented for this, we would be interested in that as well).

Thank you!

**Comment by myedibleenso** [comment]
>Does Odinson have an API component to extract mentions from a single fragment of text (as opposed to a corpus)?

@adarshp , the easiest way to accomplish this would be to use an in-memory index.  The tests linked below illustrate how an `ExtractorEngine` can be initialized with such an index:

https://github.com/lum-ai/odinson/blob/9d0edd78b875147cfb5cbb38205f0cdcbeb1e401/core/src/test/scala/ai/lum/odinson/foundations/TestExtractorEngine.scala#L26-L93

You will need to preprocess your text and convert it to one or more Odinson Documents.  If you're using [`clulab/processors`](https://github.com/clulab/processors/) to preprocess and enrich your text fragments, the Odinson `extras` package provides some utilities for converting an `org.clu.processors.Document` to an `ai.lum.odinson.Document`:

https://github.com/lum-ai/odinson/blob/9d0edd78b875147cfb5cbb38205f0cdcbeb1e401/extra/src/main/scala/ai/lum/odinson/extra/utils/ProcessorsUtils.scala#L48-L54


>is Odinson backward compatible with Odin rules?

No. Each of those systems has features the other does not.  

In some cases, Odin rules will work out-of-the-box with Odinson:

- https://gh.lum.ai/odinson/event_queries.html

Here are some of the key differences that immediately come to mind:

- Odinson does not support actions
   - You would need to write your own logic to achieve this.
- Odinson does not (yet) support embedding-based matchers
   - We don't yet have a definite timeline for this enhancement.
- Odinson does not support cross-sentence patterns  
- Odin does not support hybridizing graph traversals with surface patterns.  
   - In Odin, it is only possible to specify constraints on nodes in the traversal.

**Comment by adarshp** [comment]
Thank you @myedibleenso ! This is super helpful. Will have to mull over this a bit.

- While we do have actions, it might be worth reimplementing their logic to switch to Odinson.
- I don't think we use embedding-based matchers, but I'll have to double-check.
- Most of our utterances are single sentences, so the lack of cross-sentence pattern support should not be an issue.
- The hybridized graph traversals sound intriguing, and another reason we might want to try Odinson.

Another quick question - is the browser-based interface shown in Figure 1 of the Odinson paper (https://aclanthology.org/2020.lrec-1.267.pdf) still available somewhere, or has it been deprecated? I couldn't find it in the Odinson docs.

FYI @remo-help, @Yuweien, @chencc33

**Comment by myedibleenso** [comment]
The UI referenced in the paper has been removed from the project.  @BeckySharp created a separate UI (https://github.com/BeckySharp/OdinsonWebapp), but I'm not sure if it is compatible with the latest release of Odinson.

[lum-ai](https://github.com/lum-ai) has discussed providing a basic UI as a standalone project, but at this time we're not ready to commit to maintaining something like that (FYI @danebell ).  That said, Odinson patterns will feature in our rapid annotation platform (probably in its second or third release).

**Comment by adarshp** [comment]
Thanks @myedibleenso - totally understand, UI development and maintenance is very labor-intensive. I'll check out @BeckySharp 's UI.
