### ISSUE TITLE
Search results order based on  document id (not lucene id)

### ISSUE THREAD

**Issue by mcshlain** [lum-ai/odinson#38]
**Is your feature request related to a problem? Please describe.**
This a continuation of  #20 that changed the behavior of search to return the results in the order of the internal lucene id. We would like to have the sesrch results order correspond to the defined extranal document ids and not the internal lucene id.

**Describe the solution you'd like**
I propose a simple workaround to load the documents into the index in the order of the document ids, this way the order induced by the lucene id will match the ordering of the document ids.
This should be controllable by configuration, as it will slow the indexing process and will not be needed in all scenarios. 

**Additional context**
A PR is available here: #37

**Comment by marcovzla** [comment]
Closed by #37
