### ISSUE TITLE
Documentation link is not working

### ISSUE THREAD

**Issue by svempati21** [lum-ai/odinson#389]
**Documentation type:** [End-user documentation, wiki, code comments]
Documentation link
**Improvements requested:**
The link to the documentation isn't working.
**Link (if available):**
http://gh.lum.ai/odinson/

**Comment by myedibleenso** [comment]
Thanks, @svempati21 , for opening this.  Here is the new URL for the docs: https://docs.lum.ai/odinson/

**Comment by svempati21** [comment]
Thank you! Sorry, I think it still isn't working though.

**Comment by myedibleenso** [comment]
Thanks for your patience, @svempati21 .  Can you please try https://docs.lum.ai/odinson/ again?

**Comment by svempati21** [comment]
It's working now. Thank you so much!

**Comment by svempati21** [comment]
It's working now. Thank you so much!

**Comment by svempati21** [comment]
It seems like the link to the documentation (at https://docs.lum.ai/odinson/) isn't working now.

**Comment by myedibleenso** [comment]
Hi, @svempati21 .  Sorry about that.  We changed it in the repo's side bar, but overlooked the README 😅 

Here is the new link: https://lum.ai/odinson/docs/

**Comment by svempati21** [comment]
Thank you!
