### ISSUE TITLE
How to use the pattern matcher only?

### ISSUE THREAD

**Issue by felicitywang** [lum-ai/odinson#65]
Hi,
Thanks for the great work(saw this from the AI's SPIKE-CORD demo). I'm working on information extraction(without the retrieval part) and this is very useful(your pattern matching is a lot more powerful than Spacy's rule-based matching). So it there any documentation on how to use the pattern matcher itself? There's an Odin manual but Odinson seems to have some new pattern grammar rules. Specifically, given a sentence and a pattern, I want to find the tokens that match some sub-pattern.

Thank you!

**Comment by marcovzla** [comment]
Hi!
Thanks for your interest in Odinson. We understand that documentation is important and we are currently working to release some in the very near future. We'll let you know as soon as it's ready.

**Comment by BeckySharp** [comment]
Also @felicitywang in the meantime, if you give me an example of what you're trying to extract maybe I can help you.  It won't be as thorough as good documentation ;) but just something help help until it's ready...?

**Comment by felicitywang** [comment]
@BeckySharp Thank you! So basically, for a pattern and a given sentence, the output I'm looking for is the corresponding strings for each sub-pattern. 

For example(example from README), for pattern
`(?<cause> []) <nsubj [lemma=cause] >dobj (?<increase> [lemma=increase]) >nmod_in (?<theme> []))`, 
and sentence
`Health care progress, antibiotics, vaccination and improving life standards caused a dramatic increase in lifespan in recent decades .`

I'd like the output
```
cause = ["health care progress", "antibiotics", "vaccination", "improving life standards" ]
theme = ["lifespan"]
```

For a more general example, with the pattern `(?<theme>[]) <dobj (?<predicate>[]) >nsubj (?<agent>[])` and any sentence, return a (list of) dictionary {'theme': ..., 'predicate': ..., 'agent': ...}

It seems that this is already done somewhere now that certain tokens are highlighted, yet my lack of knowledge in scala is kinda preventing me from finding/using it. 

Plus, I suppose each dependency arc has only one child, is it easy to find the enclosing phrase the token belongs to(in the example above, `improving life standards` for `standards`)? ([`expansions` in SPIKE-CORD's documentation](https://spike.covid-19.apps.allenai.org/help/search#expansions)).


Suppose I have the above issue resolved, another question is how can I use a different processor, say Spacy?

Thank you.

**Comment by BeckySharp** [comment]
ok -- so with the patterns shown above, assuming a good parse, you would get those causes and that theme.   So, it sounds like what you're really asking for is an entry point, i.e., how to actually dump that output into something.   Is that right?  

In terms of expansion, there isn't anything built in already.  That said, something we often do here, is use a rule file formatted like this:
```
vars:
  chunk: "([tag=/J.*/]{,3} [tag=/N.*/]+ (of [tag=DT]? [tag=/J.*/]{,3} [tag=/N.*/]+)?)"

rules:
  - name: example-rule
    type: basic
    pattern: |
       (?<cause> ${chunk}) <nsubj (?<trigger> [lemma=/cause|increase|decrease|affect/]) >dobj (?<effect> ${chunk})
```

The key bit here is that in the `vars` we define a poor-man's chunk (kinda an extended noun-phrase) and so when we "land" in that chunk by following the dependency arc we get the whole thing.  There are many ways to address this, but this is one we've had some decent success with.

So -- let me know about my clarification question above, and I'll try to help!

**Comment by BeckySharp** [comment]
oh! also -- yes there is a way to use a different parser.  Odinson is completely parser agnostic, you'll just have to convert your parsed documents into Odinson Documents: https://github.com/lum-ai/odinson/blob/master/core/src/main/scala/ai/lum/odinson/OdinsonDocument.scala

An example of how we convert documents created with CluLab Processors library to Odinson Documents is here, in case it helps: https://github.com/lum-ai/odinson/blob/master/extra/src/main/scala/ai/lum/odinson/extra/ProcessorsUtils.scala

**Comment by felicitywang** [comment]
Thanks! Yeah how can I get the entry point for each sub-pattern?

**Comment by BeckySharp** [comment]
Hi again -- ok @felicitywang I added an App that you can run to get started and you can use it to explore a bit.  Please take a look at https://github.com/lum-ai/odinson/blob/master/extra/src/main/scala/ai/lum/odinson/extra/Example.scala

to run it from the command line, you can do `sbt extra/run` and choose `Example` off the list.

The rules file is here: https://github.com/lum-ai/odinson/blob/master/extra/src/main/resources/example/rules.yml

and it will generate a json lines file.  You need to point it at an index in `application.conf`, if you need help making an index, there is info here: https://github.com/lum-ai/odinson/tree/master/extra

Please let me know if this helps!

**Comment by felicitywang** [comment]
Thank you! Could you tell me which environment you're using? With sbt version 1.3.10 and java version OpenJDK Runtime Environment (build 13.0.2+8), I cannot seem to compile the project with the error 
```
error: error while loading String, class file '/modules/java.base/java/lang/String.class' is broken
(class java.lang.NullPointerException/null)
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error]         at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error]         at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
...
```

**Comment by BeckySharp** [comment]
I'm pretty sure the problem is the JDK -- we target java 8

**Comment by felicitywang** [comment]
Thank you! Got it running with Java 8. 

Suppose I want to use Spacy(in Python) to annotate the text, is it enough to annotate the texts in Python and write some .json.gz files with OdinsonDocuments' fields in docsDir as the AnnotateText.scala does and index them directly?

**Comment by BeckySharp** [comment]
great!

Exactly, as long as the files you produce have the OdinsonDocument format, you're good to go! and I actually think they don't **have** to be `.json.gz`, I think they can be `.json` too 
https://github.com/lum-ai/odinson/blob/master/extra/src/main/scala/ai/lum/odinson/extra/IndexDocuments.scala#L17

Once you have those, you'll then run `IndexDocuments` as described in the readme: https://github.com/lum-ai/odinson/tree/master/extra#indexing-annotated-documents

**Comment by psorianom** [comment]
Hi ! I thought it would be better to ask here than to open a new issue. 
Is it possible to share (or maybe it is already available) a JSON example of an OdisonDocument ? I am not very good with scala :/

Thank you for your work !

**Comment by BeckySharp** [comment]
cool! I like the idea, though, and will definitely add one soon so people don't have to go digging!
thanks for the suggestion!

**Comment by BeckySharp** [comment]
@felicitywang should we close this issue? or are there outstanding concerns?
thanks!

**Comment by felicitywang** [comment]
@BeckySharp Thank you for all the help. Closing for now.
