### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PeterAJansen** [lum-ai/odinson#75]
Would there be any documentation available for getting odinson running, usage, API, documentation on the language, etc?

**Comment by myedibleenso** [comment]
Hi, @PeterAJansen .  We're actually in the middle of a big push to improve our documentation.  We have plans for tutorials, videos, and a public demo.  Right now, though, I'm afraid things are fairly limited.  I'm sure you've seen the README already.   This issue points to some examples apps:

- https://github.com/lum-ai/odinson/issues/65#issuecomment-626054745

The rule language is _based_ heavily on Odin (most Odin rules are valid Odinson rules).  Unfortunately, we don't yet have a new manual for Odinson detailing changes to the language.

**Comment by PeterAJansen** [comment]
Thanks @myedibleenso .  Is there handy documentation/materials from your tutorial for getting started with the old ODIN?  I'm trying to get a student booted up, and if she can start with the old ODIN then most of the skills will likely transfer?

**Comment by myedibleenso** [comment]
As far as an intro to the Odin language, the interactive tutorial I developed might be a good place to start:

- https://github.com/clu-ling/odin-tutorial

I'll follow up with instructions for setting up an Odinson project in Scala.  

If you want to use Odinson outside of Scala, we have a REST API with an OpenAPI specification of its endpoints and data models:

- https://github.com/lum-ai/odinson/blob/master/backend/public/schema/odinson.yaml

**Comment by PeterAJansen** [comment]
Thanks!

Having a quick look at the API, it looks like we'd still have to wait for the documentation to learn how to generate the index on our target corpus before being able to use the Odinson REST API?

**Comment by myedibleenso** [comment]
He have an example runnable for annotating text using [`processors`](https://github.com/clulab/processors) to produce [Odinson Document](https://github.com/lum-ai/odinson/blob/master/core/src/main/scala/ai/lum/odinson/OdinsonDocument.scala) JSON:

- https://github.com/lum-ai/odinson/blob/master/extra/src/main/scala/ai/lum/odinson/extra/AnnotateText.scala

Here is an example runnable for generating an index:

- https://github.com/lum-ai/odinson/blob/master/extra/src/main/scala/ai/lum/odinson/extra/IndexDocuments.scala

Unfortunately, the Odinson Document JSON is not well documented.  If you're wanting to use something other than `processors` to annotate text (ex. SpaCy), the best advice I can provide at this time is to annotate a few text files using the runnable linked above, and examine the structure of the JSON.

**Comment by BeckySharp** [comment]
@PeterAJansen Glad you're looking into Odinson, and if you have questions in the meantime of documentation, ask away, we're actively working on it.  In addition to the links @myedibleenso posted, we have a readme in `extra` that describes some of the "setup" stuff (i.e., annotating to get the Odinson Documents, making the index, querying in the shell, etc.): https://github.com/lum-ai/odinson/tree/master/extra

**Comment by PeterAJansen** [comment]
You guys are great!  This should definitely get us started!

**Comment by PeterAJansen** [comment]
In the interim while the documentation is being constructed, is there a forum or google group to ask odin syntax questions on?  I've been trying to figure out how to properly express multi word expressions in variables (e.g. myvar: "blue cat | purple dog") and can't seem to find it in the regular ODIN documentation (and i'm sure have plenty of other dumb questions as I learn the language)

**Comment by myedibleenso** [comment]
We don't have a mailing list, but that's a really good idea. Let me take a look at setting something up...

**Comment by PeterAJansen** [comment]
e.g. here's one for another domain-specific language, where folks ask basic questions: 

https://groups.google.com/forum/#!forum/choco-solver

**Comment by myedibleenso** [comment]
I'm going to update the README with a section related to this, but I've gone ahead and created two groups.

- Odin forum: https://groups.google.com/d/forum/odin-ie
- Odinson forum: https://groups.google.com/d/forum/odinson

**Comment by gcgbarbosa** [comment]
I have worked with https://gitter.im/ in other projects and it is also a great option in my opinion.
We could have a badge on both repos with it.

**Comment by BeckySharp** [comment]
@PeterAJansen note that #82 made some progress on the State -- look especially at the tests that changed.  It's still WIP but wanted to ping you so you knew
