### ISSUE TITLE
Memory usage for annotation/indexer stage

### ISSUE THREAD

**Issue by PeterAJansen** [lum-ai/odinson#93]
It looks like the annotator in the indexer step can require a fair amount of memory, and occasionally crashes with out-of-memory errors, but the memory requirements aren't currently mentioned in the documentation. 

export SBT_OPTS="-Xmx32g" seems to show about 22g of usage for 32 threads in a corpus of 40k documents between 200 bytes and ~2MB each.  The error when it was crashing was very long (and across threads), so it was easy to miss the out of memory error burried in there -- it seemed to be throwing an error on a null, so I initially thought it was an issue with invalid characters or some other parse error on the dataset. 

Seems to run much faster with more memory too.

**Comment by BeckySharp** [comment]
closing bc I think it's resolved, but please reopen if I am wrong!
